Update links and Module 1
Amii-Open-Source/awesome-amii-hpc pull request #7
Opened 2024-05-27 07:56 UTC by userseSE

I rearranged links in README and modified contents in Module 1. 

And I have two questions to be fixed:
- maybe I should delete the links for other courses in README? 
- are the photos I chose in Module 1 usable? I didn't find any related photo for Compute Canada, if the photos now are not usable I may draw them by myself. 

Btw, I'm a little confused about module 4 - When should I use a cluster, I feel like no link is suitable to be put here, and what could I expand to talk in this module? I can only think out two paragraphs now to describe different types of tasks for HPC and PC respectively, which are covered in syllabus.

2024-05-27 16:12 UTC, andy-amii commented
Good questions!

1. There's a good chance we won't have any links for module 4, that's okay!
2. I think just the Vlaams image is the only one that I'd remove. Mostly concerned it might confuse new users since it's for a european machine. But I think you covered the important points pretty well already, anyways!

2024-05-27 16:12 UTC, andy-amii requested changes

2024-05-27 16:12 UTC, andy-amii commented on Module 1 - What is a cluster.md
> +![Tiering model. Photo by https://static.wixstatic.com](https://static.wixstatic.com/media/5446c2_002fa8b33249455b80a94926fc81cc26~mv2.jpg/v1/crop/x_0,y_118,w_1015,h_482/fill/w_1015,h_482,al_c,q_85,e
I think I would go ahead and drop this image. The bullet points above are clear enough on their own.

2024-05-27 16:58 UTC, userseSE commented
Sounds good! the image is removed

2024-05-28 14:11 UTC, andy-amii approved these changes

2024-05-28 14:11 UTC, merged